version: "3.8"

services:
  goydazvon-demo:
    image: ghcr.io/nrf24l01/goydazvon_preview/goydazvon_demo:latest
    container_name: goydazvon-demo
    ports:
      - "8002:80"
    restart: unless-stopped